name: deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: SAST test

    runs-on: ubuntu-latest

    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'javascript'

      - name: Perform CodeQWL Analysis
        uses: github/codeql-action/analyze@v3
