name: deploy

on:
  push:
    branches: ["main"]

env:
  REGISTRY: cachac
  IMAGE_NAME: rest_api

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            APP_ENV=${{ secrets.APP_ENV }}

  loadTest:
    name: Load Testing
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install -g artillery
          npm install --save-dev artillery-plugin-ensure

      - name: Run container
        run: |
          docker run -d --name rest-api -p 3000:3000 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Run Load Test
        run: |
          set -e  # Detiene el workflow si la prueba de carga falla.

          artillery run loadTest/basic.yaml || exit 1