name: deploy

on:
  push:
    branches: ["main"]

env:
  REGISTRY: cachac
  IMAGE_NAME: rest_api

jobs:
  build:
    name: DAST Test
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'javascript'
    

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
